name: AI Integrated Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run_hello_world:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Run Python script
        run: |
          echo "print('Hello, World!')" > hello.py
          python hello.py